### PR TITLE
Update Build Offline with latest features

### PR DESCRIPTION
**Pull request by clint-tseng**
Plus, change the UI to be multi-window, which makes it more desktop-like.

WIP. Not yet ready.

### CODE REVIEW

**Comment by clint-tseng** [comment]
Okay, this should now be ready for review and n*sync with the latest online release build, so we can push both at once.

**Comment by clint-tseng** [comment]
(I'd probably advise going through each commit rather than the full diff as that diff includes already-reviewed work off `master`)

**Comment by lognaturel** [comment]
I attempted to try this out by running `nwjs .` from my Build root directory. Runs great except that none of the icons are showing up (+ for adding a control, x for deleting a control, control images, etc) and Save/Save as and Export to XML/XLSForm aren't working. I'm seeing 
```
Error: Cannot find module 'build2xlsform'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)
module.js:496
    throw err;
    ^

Error: Cannot find module 'request-digest'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)
```

Did I run it correctly? It would be good to have this documented in the README.

**Comment by clint-tseng** [comment]
Did you `make`?

**Comment by clint-tseng** [comment]
Readme is [here](https://github.com/opendatakit/build/blob/offline/README.textile).

**Comment by lognaturel** [comment]
`make` both in this branch and the base offline branch gives me `cp: node_modules: No such file or directory`.

When you have a chance, it'd be good to have a link to the branch readme from the main readme. I should have thought to look but still, it'd be nice to have a section that describes the offline tool's existence.

**Comment by clint-tseng** [comment]
I'll update the Makefile to include `npm install`. For now, run `npm install` then `make`, then `make go` should launch.

**Comment by clint-tseng** [comment]
(maybe throw a `make clean` in there to be safe)

**Comment by lognaturel** [comment]
Cool, that worked. `make go` didn't but I think that's some kind of path issue. I was able to explicitly call `nwjs` on the `.nw` file.

**Pull request merged**
