### PR TITLE
Drag/drop rewrite; multi-select; minor annoyances

### PR DESCRIPTION
**Pull request by clint-tseng**
**Note:** PR #114 has been merged into this one to resolve some merge conflicts. Please refer to both PR notes for a comprehensive look at this PR.

This PR tackles three related major areas:

- It rewrites drag and drop completely:
    - It fixes a lot of the weird gremlins and tics that the old system had.
    - It greatly reduces our reliance on heavyweight 3rd party code.
    - It allows duplicating-drag when `ctrl` or `option` are held.
    - It allows cross-window drag between documents.
- It introduces control multi-select:
    - It allows range-select when `shift` is held.
    - It allows single multi-select when `ctrl` or `cmd` is held.
    - It allows multiply-selected controls to be dragged at once.
- It revamps the help and hint system:
    - It allots a new space below the properties pane for help information.
    - It reacts dynamically to the user's actions, providing contextual help.
    - It provides help on: control types, property types, drag-and-drop, and multi-select.
    - It, in doing so, exposes some features that were previously virtually unknown, like `${substitution}`.

Known bugs and/or limitations:

- Microsoft-based browsers will always copy when moving controls between windows.
- IE 10 has intractable problems calculating drag-drop drop position, so has suboptimal behaviour.
- Many browsers will not display an appropriate icon whilst dragging multiple controls at once.
- Chrome can behave strangely if a key is held while changing window focus.

Tested during development:

- Drag drop:
    - macOS 10.12: Chrome, Firefox, Safari
    - Windows 10: Edge, IE11, IE10
    - Drag within window
        - Drag amongst siblings
        - Drag from bottom toolbar
        - Drag to empty space at bottom
        - Drag to empty space at top
        - Drag into the gap between controls
        - Drag into a group
        - Drag out of a group
        - Drag between sibling groups
        - Drag between groups nested at different levels within a common ancestor group
        - Drag just above a group
        - Drag just below a group
        - Drag into the gap at the start of a group's subcontrols
        - Drag into the gap between a group's subcontrols
        - Drag into the gap at the end of a group's subcontrols
        - Drag an entire group
        - Drag an entire group into another group
        - Drag an entire group out of another group
        - Initiate drag but drop where the control originated
        - Initiate drag but drop where the group originated
        - Attempt to drag an entire group into itself
    - Duplicate within window
        - Duplicate a control as a sibling
        - Duplicate a control into a group
        - Duplicate a control out of a group
        - Duplicate causes validation error
    - Edge-scrolling
        - Native auto-scroll near top and bottom in Chrome, Edge, IE
        - Artificial auto-scroll near top and bottom in Safari, Firefox
        - Scroll ceases upon range exit or drop
    - Drag between windows (not IE, Edge)
        - Drag one control amongst many between windows
        - Drag the only control out of a window
            - Subsequently drag a control back into that window
        - Drag into an empty canvas
        - Drag into a document causing validation errors
        - Drag out of a document relieving validation errors
        - Drag an entire group between windows
        - Drag into a group between windows
        - Drag out of a group between windows
        - Drag non-ODK Build content into a window
        - Drag ODK Build content into other receptacles
        - Drag uses appropriate mouse visuals
        - Drag a control back and forth repeatedly does not cause degradation
    - Duplicate between windows
        - Same test cases as drag
        - Duplicate uses appropriate mouse visuals
        - Special Chrome handling of duplication works as expected
- Multiselect
    - Selection
        - Select single control works
        - Toggle selection of multiple controls via `ctrl`/`cmd`
        - Selecting multiple controls updates property pane, help area with message
        - Unselecting all controls by holding `ctrl`/`cmd` works and updates property pane
        - Single-selected control is subsequently toggleable via `ctrl`/`cmd`
        - Single select clears multi-selection
        - Range-select with `shift` works amongst siblings
        - Range-select uses initial single-select as anchor
        - `Shift`-clicking on the range-select anchor does nothing
            - Subsequently range-selecting by `shift`-clicking another control works in both directions
        - Range-select from anchor in one direction then in the other direction acts appropriately
        - Toggle-select via `ctrl`/`cmd` establishes new range-select session (subsequent range-select is independent of any previous)
        - Range-select across already-selected controls selects everything
        - Range-deselect across variously-selected controls deselects everything
        - Range-select highlights appropriate controls from a higher group level into a deeper group level
        - Range-select highlights appropriate controls from a deeper group level into a higher group level
        - Range-select highlights appropriate controls across sibling group subcontrols
            - When there are controls between the groups
            - When there is nothing between the groups
        - Range-select highlights appropriate controls across multiply-nested sibling group subcontrols
            - When the initiator is deeper
            - When the target is deeper
        - Range-select across a group highlights the group and all its contents
            - When the group is at the top level of the selection
            - When the group is nested in a group within the subcontrol selection
        - Range-select initiated or terminated on a group works
        - Range-select initiated or terminated on a group highlights all subcontrols
    - Drag, duplicate
        - Same test cases as single-select
        - Drag noncontiguously selected controls into a group
        - Drag noncontiguously selected controls out of a group
        - Drag range-selected controls within its own range
        - Appropriate drag visual is displayed (not Edge/IE)

### CODE REVIEW

**Comment by lognaturel** [comment]
This is super epic. 👏👏 Thanks for doing all of this, it's a huge upgrade.

Here are some things I noticed in a first pass:
- Clicking on a check in the View menu means the menu stays visible. In the case of Collapse Questions, it means the meaning of the check gets reversed. (We talked about this in Slack)
- Moving several controls reverses their order. Name controls 1-3, select all of them, move them, they're in order 3-1.
- Label text is lost when copying or moving controls to another window. No sign of them when exporting to XML, either. They do show up if the control is dragged back to the original window.
- I don't know how typical this is but I opened up a form that had controls named untitled6, ..., untitled5. So the next control I added defaulted to being named untitled6. (It is not marked as a duplicate which I think is actually is the same as the next issue.)
- If I copy a control that was saved in a form before I opened it this session, I can leave the duplicate data names with no warnings. On the other hand, controls that I add in this session can't have duplicate names.
- If I save a form and then immediately go to new form, I still get the "Are you sure? You will lose unsaved changes to the current form." popup.
- This is mostly a personal preference but I would expect clicking on the background or just outside of any control to clear my current selection.
- This can easily be kept for later but it would be nice to have a way to delete the selected controls.

**Comment by clint-tseng** [comment]
Let's get #1, #4, #7, and #8 in your list filed as separate issues that can be independently prioritized/addressed.

**Comment by lognaturel** [comment]
Sure. I'll do another pass once the couple of bugs are ironed out and file issues for the things that can be handled later at that point.

**Comment by clint-tseng** [comment]
2, 3, 5, and 6 in your list are resolved.

**Pull request merged**
