### PR TITLE
server/new #74: allow login/reset password via email address.

### PR DESCRIPTION
**Pull request by clint-tseng**

### CODE REVIEW

**Comment by lognaturel** [comment]
So sorry about the delay on this. Every time I've tried to check the behavior I've run into a road block and then wandered off. I should probably just ask you.

First thing is that I get 404s for all the javascript and css. Can't seem to figure out why since that hasn't changed in this PR. Seems if I first run from master, then run from this branch, I get some styling.

Except that then it just is stuck forever at "checking who you are." 404 for /javascripts/auth.js

**Comment by clint-tseng** [comment]
How are you running the server? From which dir?

**Comment by lognaturel** [comment]
I run it from the root dir since that's where the config.ru file is. 

But somehow I hadn't noticed that my local master branch was behind (pre-moving things to the server folder). I've now updated it and have the same problem.

**Comment by clint-tseng** [comment]
And `git status` is clean against this rev?

**Comment by lognaturel** [comment]
Yup. And same problem with master, now.

**Comment by clint-tseng** [comment]
Are you using `rbenv` or `rvm` or some related Gem manager to make sure your dependencies are clean?

**Comment by lognaturel** [comment]
I do use `rbenv` but I don't know how much sense it makes for me to try to hunt this issue down. You're going to merge in the vagrant stuff soon, right? I can just review assuming you've verified the behavior. Code looks fine. I'm not so sure about the look of the "/Email" hint and that's what I wanted to see but it's not a big deal.

**Comment by lognaturel** [comment]
Please take a look at the build error on CircleCI when you have a chance - https://circleci.com/gh/opendatakit/build/63

**Pull request merged**
