### PR TITLE
Merge all changes for 0.3.3 into offline

### PR DESCRIPTION
**Pull request by clint-tseng**
This includes the new PR #177 just submitted.

Everything merged cleanly and it looks copacetic, so this shouldn't require deep combing.

### CODE REVIEW

**Comment by clint-tseng** [comment]
This PR doesn't look like what I pushed. Standby one.

**Comment by clint-tseng** [comment]
Okay yes I did several things wrong but it is all fixed now.

**Comment by clint-tseng** [comment]
@lognaturel I'm going to cut the release off this PR even though you haven't signed off, since it is very straightforward.

**Comment by lognaturel** [comment]
👍

It seems like every time I try to run offline I have a new problem with `nwjs`. But I finally did just get it to run and all looks good.

**Comment by clint-tseng** [comment]
That's so weird! What was the problem this time?

**Comment by lognaturel** [comment]
Well, `make go` isn't finding it for some reason. And then when I ran it directly I was getting the same issue as before as though I had accidentally upgraded it again. So I had to downgrade again and now all is good.

**Comment by lognaturel** [comment]
Until next time I try to use it. 😄😭

**Comment by clint-tseng** [comment]
Ahhhh I see. I forgot about `make go` so I don't use it, I just `^R` in terminal to find my most recent instance of "nw". 😂

**Pull request merged**
