### PR TITLE
Additional form properties

### PR DESCRIPTION
**Pull request by clint-tseng**
Save, load, XML-export, UI, and help text for:

* instance name
* public key
* submission url

XLSForm-related changes can be found at https://github.com/opendatakit/build2xlsform/commit/14ff48c57ca94fd2b6f65d8d62f2616c474eb07a

### CODE REVIEW

**Comment by lognaturel** [comment]
I have some bad news. There's no penalty for the `orx:meta` namespace non-compliance but there actually is a penalty for compliance - opendatakit/javarosa#60. I think this will be out in JavaRosa by the end of the month but I'm not sure when it will make its way to Aggregate. Probably best to hold off on that (good) change for a bit. 😢

**Comment by clint-tseng** [comment]
I will duly ignore the xforms-spec information from here on out! 😂

**Comment by lognaturel** [comment]
Nooooooo!!! 😱😱😱

**Comment by clint-tseng** [comment]
`orx` namespacing has been removed; ready for re-review.

**Comment by lognaturel** [comment]
Submission URL and public key work well. XLSForm looks good.

I don't think instance name is quite right. It looks like the value is currently just being put in the node. It should be like `instanceID` with a bind and a calculate.

For example, if I put in `concat(/data/untitled1, ' is dope')`, I should get something like
```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
  <h:head>
    <h:title>Untitled Form</h:title>
    <model>
      <instance>
        <data id="build_Untitled-Form_1500582733">
          <meta>
            <instanceID/>
            <instanceName/>
          </meta>
          <untitled1/>
        </data>
      </instance>
      <itext>
        <translation lang="English">
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
      <bind nodeset="/data/untitled1" type="string"/>
      <bind nodeset="/data/meta/instanceName" type="string" calculate="concat(/data/untitled1, ' is dope')" readonly="true()"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/untitled1">
    </input>
  </h:body>
</h:html>
```

As a side note (and I'm sure this is no surprise), calculates are really hard to use. I had to know what the root node is called and use the XML syntax. The docs the hint points to is the XLS syntax. I'm not sure that anything needs to be done now but it's something we should talk about. As a first step, it might be educational to find out if people do use calculates.

**Comment by clint-tseng** [comment]
Ah; I see. [This wording](https://opendatakit.org/help/form-design/examples/) could maybe be made more explicit then:

> This is implemented within the XML as an instanceName field within the meta block. If this value is present and not an empty string (""), it will be used as the name of the filled-in form. Otherwise, the current default naming, based upon the date the form was first saved, will be used.

**Comment by clint-tseng** [comment]
Updated; ready for re-review.

**Comment by clint-tseng** [comment]
As for calculate: yes, but that's a much bigger discussion and a Build rewrite.

**Pull request merged**
