### PR TITLE
Freeform language options

### LINKED ISSUE #55: ODK Build:  Unsupported languages and ordering
<a href="https://github.com/mitchellsundt"></img></a> **Issue by [mitchellsundt](https://github.com/mitchellsundt)**
_Thursday Jul 09, 2015 at 17:31 GMT_
_Originally opened as https://github.com/opendatakit/opendatakit/issues/156 (2 comment(s))_

----

Originally reported on Google Code with ID 155

```
When adding language translations the languages are not in order.  For example, "Spanish"
shows up near most of the E's, but appears on the phone as "SPA".  

I'm not sure if this is possible, but it'd be nice if the whole word "spanish" showed
up on the phone instead of "spa"

Also, in several trainings users have asked what they should do when a local dialect/language
is not on the list.  There's no way right now to add or specify another.

It may be easier to just make the add a field where you type the language name and
click "add".?  Haven't thought it through much, so not sure what the easiest/best thing
to do would be.
```

Reported by `carlhartung` on 2010-12-09 17:30:36

### LINKED ISSUE #91: When restarting the Build, added languages were not shown in the View menu.
Hi there.

Thanks for developing the ODK Build.  I found an issue on the multi language setting.  When I create a form in more than two languages, the language can be added at the "manage translation" of the Edit menu.  I then can switch a displayed language at the View menu.  Let's say, I can add/switch English to Japanese.  These functions work fine.  

However, once i close the browser and sign in the ODK Build again, and open the saved form with multiple languages, the View menu only shows "English" on the list.  To solve this issue, I have to add Japanese language at the "manage translation" menu every time in a blank form page before i start form editing.  

Also, if i delete English from the translation list, it comes back every time when i restart the browser.  I think this happens because English is considered as the default language in the ODK Build.  I don't know if improving this issue is hard, but it should be helpful for ones creating forms with multiple languages. 

Thanks.

### PR DESCRIPTION
**Pull request by clint-tseng**
Allows users to type their own language names rather than selecting from the list of ISO-languages, which resolves #55. This PR also fixes #91.

Previously, languages were stored as an array of ISO codes. The strategy here is to move from an array to a hash mapping, and for custom new languages to generate integer codes. So a typical migrated `activeLanguages` databag might look like `{ _counter: 2, _display: "eng", eng: "English", esp: "Spanish", 0: "Cool Language", 1: "Cooler Language" }`. The `_counter` key stores the current increment count for generating integer codes, and the `_display` key keeps track of which language the user has active from the View menu.

As a side effect, the outputted language to XML and to XLSForm is now the full language name rather than a three-letter ISO-code. This means that in Collect it'll display the language name rather than the code as well, but it also means dirty text (whitespace, etc) can get into the XML attributes/XLSForm headers. Having checked with the XLSForm reftable, ODK Validate, and a cursory look at the ODK Collect codebase, I don't believe this should pose a problem, but y'all'd know better than me.

### CODE REVIEW

**Comment by clint-tseng** [comment]
Ugh, this isn't ready to go yet. I forgot to implement language rename. I'll get that ready for tomorrow.

**Comment by clint-tseng** [comment]
Okay, this is ready now @lognaturel !

**Comment by lognaturel** [comment]
I think the best way for me to provide quality control here would be to make sure that you've considered all weird cases. I don't think I can identify any issues looking at the code. Do you have a list of the things you specifically verified? Things like "export multiple languages", "form with multiple languages before upgrade", etc? I'm going through and making my list as I go.

**Comment by lognaturel** [comment]
- Open form from previous version that only had English
- Open form from previous version that only had one language other than English
- Open form from previous version that had multiple languages
- Export form with multiple languages to XML
- Remove all languages
- Rename language
- Load from .odkbuild file generated from older version

All that works well. What did I forget?

Apologies if I'm missing something obvious but why treat "known" languages differently? I can't see the language code being used for anything other than keeping track of what the default language is. Why not just number those too or use a flat list to keep track of a form's languages? Is it purely for backwards compatibility?

This is a tiny thing but the text boxes aren't aligned when adding languages:
screen shot 2017-04-10 at 10 25 55 am

One thing that I found confusing is that if I have a form with multiple languages open and then create a new one, the side pane still shows the info from the last field I was looking at in the old form. Then, if I remove a bunch of languages, they still show up in that phantom side pane. I think that when a new form is created, the side pane should be blanked out. This is not something for this pull request but I wanted to mention it.

**Comment by clint-tseng** [comment]
Known languages are 100% for backwards compat. The data is already saved per-field under the three-letter code and since dynamically typed lookups are free in JS I saw no reason to take undue risks and try changing every single one.

I.. don't think I care about the textbox alignment?

The new form issue is fixed in `minor-annoyances`.

**Comment by lognaturel** [comment]
Can you please do me a favor and fix the alignment in `minor-annoyances`? Should be easy, right??

**Comment by clint-tseng** [comment]
Getting them to be perfect in every browser on every operating system is probably an hour's worth of work. Worth it?

**Comment by lognaturel** [comment]
Sigh. Really, in 2017?! Ok, fine, let it be. But please tell me it's aligned in SOME browser(s).

**Comment by clint-tseng** [comment]
Probably! 😂

**Pull request merged**
