### PR TITLE
all/new #157: add range widget.

### PR DESCRIPTION
**Pull request by clint-tseng**
* also spruce up bindDisplayIf to check against things other than bools.
* also spruce up validation to not validate if the property isn’t shown.
* still need to update opendatakit/build2xlsform for this feature.

### CODE REVIEW

**Comment by clint-tseng** [comment]
Also: https://github.com/opendatakit/build2xlsform/commit/12a1f5b76343a70bacfe6c2ae7daea19a7e7697f

**Comment by clint-tseng** [comment]
Hmmmm I bet if one entered `0` for `step` it'll happily and erroneously accept it as `Math.floor(Infinity) === Infinity` evaluates to `true`. I'll have to add a check for that.

**Comment by lognaturel** [comment]
When I choose a style other than textbox, I don't seem to be able to export to XML! No error in Build or on the console.

**Comment by clint-tseng** [comment]
Ha, that was subtle. Only happens if you accept the default values. I also fixed `step` to reject zero or less. Should be ready for re-review.

**Comment by lognaturel** [comment]
Ooh, it didn't occur to me to try changing the defaults. Fun bugs! 

`build2xlsform` looks great. There's one more thing I realize I forgot to mention for the XML. There is an expectation of a `type` on the bind. In XLSForm it's inferred from the arguments and I think Build should do the same. And also, I'm sorry, I know it seems it shouldn't be necessary but there you go...

**Comment by clint-tseng** [comment]
`type` is now inferred and added to the binding.

**Pull request merged**
