### PR TITLE
#69: convenience generator for followup questions

### PR DESCRIPTION
**Pull request by clint-tseng**
See commit messages for further detail.

### CODE REVIEW

**Comment by yanokwa** [comment]
Really loving how this turned out. And I can confirm it works well with field-lists and groups. Great job, @clint-tseng! 

My issue before merge is, how best can I verify that this works when I export to XLSForm?

**Comment by clint-tseng** [comment]
You can run it! If you run build2xlsform on port 8686 (I think I documented this somewhere but I will double check) it'll pick it up automatically in dev env.

**Comment by clint-tseng** [comment]
Actually it runs on port 8686 automatically; hence the lack of documentation on that. But I should note somewhere that the two services do in fact work in dev. Somewhere. Hm.

**Comment by clint-tseng** [comment]
@lognaturel Regarding both your bullets; yup, and yup. No perfect answers for either, and so I erred on the least-surprising option for both, which is to do nothing. Everyone hates it when software tries to outsmart them.

**Pull request merged**
