### PR TITLE
validation/refactor: completely redo the validation system.

### PR DESCRIPTION
**Pull request by clint-tseng**
* now it’s a global system that tracks from above rather than being
  bound to virtually created dom elements.
* all defined properties now live in impl.limits.js, and are self-
  contained.
* documentation on impl.limits to follow shortly.
* all old validations recreated.
* -, _, . now allowed for data names and underlying values (progress on
  #45, #46).

### CODE REVIEW

**Comment by clint-tseng** [comment]
Living PR; not quite done here yet.

**Comment by clint-tseng** [comment]
Okay, this PR is as laden as it's going to get and clears up all currently-outstanding validation issues. If someone wants to review it, it's ready.

**Comment by clint-tseng** [comment]
@lognaturel you make a good point that the names and logic should match, but I'm actually going to go the other way from your suggestion and invert the names to match the logic, because as your example demonstrates, that direction is more difficult to think about (the correct second example would read `var alphaStart = function(val) { return !_.isString(val) || /^[a-zA-Z]/i.test(val); };`)

**Comment by clint-tseng** [comment]
Never mind; I went neither direction. I left the text labels alone, and inverted the logic. But to prevent confusion of the sort that caught you up above, I've created a separated `prereq` field that's documented in-code.

**Comment by clint-tseng** [comment]
(also, the `/i` at the end of the regex already allows uppercase letters; the `i` indicates non-case-sensitive matching)

**Comment by clint-tseng** [comment]
_sigh_, looks like I had a git kerfuffle by accident. The real diff to be reviewed is https://github.com/opendatakit/build/compare/0b90447...cxlt/validation-refactor (feel like reading a much bigger diff, @lognaturel ?) :/

**Comment by lognaturel** [comment]
Phew! Sorry about the delay, that diff was a lot to digest. I wanted to at least have enough context to understand the big ideas. 

Following up on our naming and boolean expression conversation, I really like the way you split out prereq/check and I think validations are now pretty easy to create which is fantastic. I didn't see any obvious bugs although I must admit there are a few things I didn't do a deep dive in.

**Pull request merged**
